site_name: Pydantic Factories
repo_url: https://github.com/Goldziher/pydantic-factories
repo_name: Goldziher/pydantic-factories
site_url: https://starlite-api.github.io/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
        lang: en
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search:
      lang: en
